### ISSUE TITLE
Add support for selecting the parent for the picker

### ISSUE THREAD

**Issue by brenjt** [indrimuska/angular-moment-picker#107]
It would be very useful if I could specify the parent element for the picker to be placed in. This would help when the picker is used inside of elements that are overflow:scroll or hidden.

![image](https://cloud.githubusercontent.com/assets/1713885/21698602/efb42404-d354-11e6-9776-2198d1d59a75.png)

**Comment by indrimuska** [comment]
Hi @brenjt, I think this should be the next feature. And it will! :)

**Comment by indrimuska** [comment]
Hi @brenjt, I've just pushed a [new release](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.10.0) of Angular Moment Picker which appends the picker to the `document.body` instead of using a relative position to the given element.
With this feature in place, I'm going to close this issue. Feel free to reopen it again if it does not satisfy your needs.
Thanks!

**Comment by easyest** [comment]
And this made moment picked completely unusable in popups that rely on event propagation...

**Comment by easyest** [comment]
For those of You that have problems with picker in bootstrap drop-down menu (picker click closes the drop-down menu), add this line
```
$scope.container.click(function (e) { e.stopPropagation(); });
```
after the line
```
$scope.container = angular.element($scope.picker[0].querySelectorAll('.moment-picker-container'));
```
