### ISSUE TITLE
Input group bug

### ISSUE THREAD

**Issue by emREVENGER** [indrimuska/angular-moment-picker#108]
I have some troubles when I'm using the input group since 1 week. When I'm selecting a time, the value is not bind on the view. I fixed it temporary by adding the moment-picker inside the input
Before :
![capture d ecran 2017-01-09 a 01 11 11](https://cloud.githubusercontent.com/assets/4700465/21754827/8a3bd4da-d608-11e6-9059-6f74139f4a1e.png)

After change :

![capture d ecran 2017-01-09 a 01 08 41](https://cloud.githubusercontent.com/assets/4700465/21754815/44469d16-d608-11e6-8747-d9a63a5d7eeb.png)

I don't know if the problem is come from me or the library.

**Comment by indrimuska** [comment]
Hi @emREVENGER,

Starting from version 0.8, I've refactored the project in order to let people use full Moment.js object instead of using just strings.

This causes a minor breaking change for those who use Angular Moment Picker with input fields: as you can see from the [README](https://github.com/indrimuska/angular-moment-picker#options), now the property you use for two-way binding with `ngModel` should be a Moment.js object, rather then the property for `momentPicker` still remain a string.

To be clear, you can use both variable this way:

```html
<div class="input-group" moment-picker="timeFormatted" format="HH:mm:ss">
    <span class="input-group-addon">
        <i class="octicon octicon-clock"></i>
    </span>
    <input class="form-control" placeholder="Select a time" ng-model="timeMoment">
</div>
```

---
I just notice that Demo page has older incorrect examples for this use-case I must update as soon as possible. Thank you for reporting this. :)

**Comment by indrimuska** [comment]
Got it! Let me fix it in a minute!

**Comment by indrimuska** [comment]
FYI, this fix will be available in the next release.

**Comment by indrimuska** [comment]
Latest release [v0.9.2](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.2) is now out.
