### ISSUE TITLE
When using ng-model, moment-picker attribute doesn't bind

### ISSUE THREAD

**Issue by ChrisGarber-Medlever** [indrimuska/angular-moment-picker#112]
If a moment-picker is set up like so:

`<input moment-picker="foo" ng-model="bar">`

then modifying/deleting foo will not update bar. Modifying bar works wonderfully, and foo is updated.

Plunker to demonstrate: https://plnkr.co/edit/D45pEiugB7rEVNdWzHmp?p=preview

**Comment by indrimuska** [comment]
Hi @ChrisGarber-Medlever, thank you for reporting this.
Give me 5 to patch a solution.

**Comment by indrimuska** [comment]
This fix will be available in the next release, I'm going to write a unit test first before release it.
In the meantime, you can have dist files by running `npm run release`.

**Comment by ChrisGarber-Medlever** [comment]
WOW that was fast, thanks so much!! You could even move that logic into the if(attrs[ngModel]) because I think that's the only time its relevant. One less watcher for efficiency?

**Comment by indrimuska** [comment]
Well, that's not completely correct, because you can change view value (property set from `moment-picker` attribute) without having to set any `ngModel` property (e.g. when using the picker with `<div>` elements).

Anyway [v0.9.3](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.9.3) is now out with this fix.
