### ISSUE TITLE
Datepicker opening after tab switch

### ISSUE THREAD

**Issue by tm-fari** [indrimuska/angular-moment-picker#118]
To reproduce : open picker, select a date, **do not click anywhere**, change browser tab, come back to datepicker's tab : the datepicker is open again.

maybe related to #102

>angular-moment-picker.js line 766
```
				// event listeners
				$scope.focusInput = function (e) {
					e.preventDefault();
					$scope.input[0].focus();
				};
				$scope.input
// Removing the 'focus' event here solve the issue but breaks keyboard tab navigation when focusing icon
					.on('focus click', function () { $scope.$evalAsync($scope.view.open); }) 
					.on('blur',        function () { $scope.$evalAsync($scope.view.close); })
					.on('keydown',     function (e) {
						if (!$scope.keyboard) return;
						e.preventDefault();
						$scope.$evalAsync(function () { $scope.view.keydown(e); });
					});
				$scope.contents.on('mousedown', $scope.focusInput);
				$scope.container.on('mousedown', $scope.focusInput);
				angular.element($window).on('resize scroll', $scope.view.position);
			});
```

**Comment by indrimuska** [comment]
Hi @tm-fari, 
Actually it is wanted that focus event will get the picker to open, and removing this will cause an unwanted breaking change (and it also removes a useful feature).

This is not due to Angular Moment Picker but to a browser behavior.

```javascript
angular.element('input').on('focus', function () { console.log('input focused'); });
```

You can see that if you change browser tab and go back to the previous one, it will always fire focus event.

Anyway, you can control picker opening/closure by handling `is-open` attribute of the directive.
Hope this helps! :)

**Comment by tm-fari** [comment]
Hi,

Thank you very much for your reply, I'll take a closer look at this 
later this week.

Thanks also for moment-picker, we were having issues with angular 
material datepicker and are quite happy now with yours!

Take care

Fahri Tardif
