### ISSUE TITLE
24h Format in minutes selection

### ISSUE THREAD

**Issue by byte369** [indrimuska/angular-moment-picker#122]
When I select year -> month -> day -> hour(23:00 for example) then next view(minutes) shows but time is not 24h formatted, but it should be cause hours view is in 24h formatted.

Any help on this?
Thanks.

![s1](https://cloud.githubusercontent.com/assets/25489753/22522526/2b300472-e8bc-11e6-9bb7-022d3534a317.png)
![s2](https://cloud.githubusercontent.com/assets/25489753/22522527/2b34621a-e8bc-11e6-88ff-6e12adc69a43.png)

**Comment by indrimuska** [comment]
Hi @byte369, use [momentPickerProvider](https://github.com/indrimuska/angular-moment-picker#momentpickerprovider) and change `minutes-format` value.
Thanks

**Comment by csimpi** [comment]
@indrimuska Unfortunately the text in the header is still in 12h format :(
 Also, in this way I can't change the 12/24h formats on the fly, the users have to reload the whole page to change the format.
Is there any better option to solve this problem? Why the minute format works differently from the other views? The other views are automatically changing the format based on the format attribute, why I have to set the minute view as a constant format in order to use the plugin?

**Comment by Tonio31** [comment]
I have the same issue, trying to change minutes-format just change the format INSIDE the calendar, not in the header.

**Comment by csimpi** [comment]
@Tonio31 Finally I had to modify the source code, there is no support here, your're on your own. I've solved the most of problems of momentpicker within 3 hours of working on the code.

**Comment by Tonio31** [comment]
@csimpi Yeah I just had a look as well and noticed the 'lll' as format in HoursView render, shame, it's not missing much to be fully configurable.

Thanks for letting me know
