### ISSUE TITLE
Disable Past date from current Date

### ISSUE THREAD

**Issue by Swatantramishra1** [indrimuska/angular-moment-picker#125]
Hi,
This is best date picker till now for angular.
I am trying to use something like this - 
Select Date picker>past date should be disabled from the today date.

**Comment by alexdunne** [comment]
@Swatantramishra1 The picker provides a callback for doing exactly this. If you look at [this example](https://github.com/indrimuska/angular-moment-picker#methods) you'll see a callback is provided for the `selectable` parameter from the parent controller. In your case, you would want to compare the date passed to the method with today's date and return false for anything that is before today.

Side note: For performance reasons you'll want to create a single `var today = new Date();` outside of the callback rather than inside as the method is called for every date in the view, every time it is rendered. I.E

```js
function MyController() {
  var vm = this;
  vm.today = new Date();

  vm.isSelectable = function (date, type) {
    // Compare date with today
  };
}
````

**Comment by indrimuska** [comment]
Thank you @Swatantramishra1 for you answer.

An alternative way to solve this is to set `minDate` property to the first selectable date you want to have in your picker. In your case, minimum date should be set to today.
Thanks.
