### ISSUE TITLE
Past time is also selectable even after setting min-date

### ISSUE THREAD

**Issue by Viren0007** [indrimuska/angular-moment-picker#129]
I have set min-date to some calendar selected date and adding time on the basis of day difference. If difference between today date and selected date is greater than 0 then adding **00:00 AM** with selected date. If 0 then adding current time of today. 

Now setting this date and time value to  second calnedar which shows time view. But when I am changing date to next day and again changes to previous day and opens time calendar then time which has past is also select able.  Here is the [plunker link](https://plnkr.co/edit/4TFkwqrQvWCQoQsyqn1V?p=preview)

Please help me why it is happening.

**Comment by indrimuska** [comment]
Hi @Viren0007, your plunker is not running (`TypeError: $filter is not a function`) since you were not adding `$filter` to the services injection list.

However I am not sure I've understood your issue, but it seems that your min date (`DateWithOneDayAhead`) has not the same format of the date you want to set (`MMMM DD YYYY`). Since I don't think that you really want to use four digit month (`MMMM` ??) this is the problem you have. In fact, after setting the format to `MM DD YYYY` I see that minim selectable date is properly set.

Hope this helps :)
