### ISSUE TITLE
Importing module gives undefined moment

### ISSUE THREAD

**Issue by Stenkilde** [indrimuska/angular-moment-picker#133]
Trying to import the module into my typescript code is leaving me behind with a "Moment is not defined" error in my console.

I am loading moment in a different bundle, together with angular.

No matter what way I try to load the module and or Moment it ends up breaking

**Comment by ChrisGarber-Medlever** [comment]
I faced this issue too. It had to do with the order I was loading my bundles I believe. Try putting them in the same bundle if you can, if not try to make sure that this bundle is loaded after the moment bundle.

**Comment by indrimuska** [comment]
Hi @Stenkilde, thank you for reporting this. I'll investigate in this.

**Comment by indrimuska** [comment]
Ok, got it. Angular Moment Picker requires the `moment` symbol already set in the global window property. Since Moment by itself does not expose that symbol when you import it using any amd/umd module loader (due to the isolated variable scope), you need to add the symbol by yourself like this:

```javascript
import * as moment from 'moment/min/moment-with-locales';
window['moment'] = moment;
```

[Attached](https://github.com/indrimuska/angular-moment-picker/files/804627/picker-sample-ts.zip) you have a very basic sample that bundles all files in a single `bundle.js` file using Webpack (run `webpack`) or FuseBox (run `node fuse.js`).

Alternatively, you can create a different bundle of Angular Moment Picker merged with Moment.js, so that you just need to do `import 'angular-moment-picker';`. In this case, change [this line](https://github.com/indrimuska/angular-moment-picker/blob/master/webpack.config.js#L29) into:

```javascript
externals: ['angular'], // avoid bundling of Angular.js
```

And run `webpack`. Output files will be available in the `dist` folder.

Let me know this solves your troubles. :)

**Comment by indrimuska** [comment]
I'm going to close this issue, feel free to open it again for any problem.

**Comment by stewebyourmind** [comment]
Hi @indrimuska I try to import moment using the suggestion above:
```
import * as moment from 'moment/min/moment-with-locales';
window['moment'] = moment;
```
but I'm facing another issue with moment locale

```
./~/moment/min/moment-with-locales.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in D:\Projects\smanager\node_modules\moment\min
 @ ./~/moment/min/moment-with-locales.js 1824:12-39
```

Do you have any idea about that?

**Comment by indrimuska** [comment]
Hi @stewebyourmind, this seems an error in your bundler configuration file.
Please check [this sample](https://github.com/indrimuska/angular-moment-picker/files/804627/picker-sample-ts.zip)

**Comment by GiampaoloFalqui** [comment]
I am trying to import angular-moment-picker with RequireJs, however it gives me the "moment is not defined" error.

Here's the requirejs configuration:

	require.config({
	  // alias libraries paths
		waitSeconds: 30,
		urlArgs: 'v=' + window.assets_version,
		paths: {
			'angular': '/node_modules/angular/angular',
			'moment': '/node_modules/moment/min/moment-with-locales.min',
			'moment-picker': '/node_modules/angular-moment-picker/dist/angular-moment-picker'
		},
		// angular does not support AMD out of the box, put it in a shim
		shim: {
			'angular': {
				exports: 'angular'
			},
			'moment': {
				exports: 'moment'
			},
			'moment-picker': {
				deps: ['angular', 'moment']
			}
		}
	});

**Comment by GiampaoloFalqui** [comment]
Solved by adding this hack:

    require.onResourceLoad = function (context, map) {
	    if (map.name === 'moment' && window['moment'] === undefined) {
		    window['moment'] = context.defined.moment;
	    }
    }

**Comment by indrimuska** [comment]
Thanks @GiampaoloFalqui for sharing a fix for RequireJs 👍

**Comment by HollyPony** [comment]
I've solve  the issue applying this : https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

In addition of your solution.

It's  solving the  warning of @stewebyourmind .

Workaround is :
```javascript
import moment from 'moment';
window['moment'] = moment;

require('angular-moment-picker') // Note: usage of  require because an `import` is forbidden after an instruction (`window['moment'] = moment`)

moment.locale('en')
```

then add  in webpack conf:
```javascript
plugins: [
  new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /en|fr/),
  ...
]
```

Anyway, I've also made a sample repo : https://github.com/HollyPony/angular-moment-picker-test

I hope it could help 🙌 ❤️ .

**Comment by j-d-b** [comment]
@HollyPony The `require` instead of `import` is key here. Thanks for this.

I believe it's related to [this](https://stackoverflow.com/questions/34563578/webpack-typescript-require-works-but-import-doesnt) rather than an "import being forbidden after an instruction".

Frustrating to debug, and I still don't entirely understand why.

**Comment by mbenedettini** [comment]
> require('angular-moment-picker') // Note: usage of  require because an `import` is forbidden after an instruction (`window['moment'] = moment`)

that one almost got me, thanks @HollyPony

**Comment by Amjad-finfirst** [comment]
@indrimuska is this issue resolved in the latest version or still we have to add these 2 lines in module manually.
