### ISSUE TITLE
Formatting of initial date when in a bootstrap input-group

### ISSUE THREAD

**Issue by mrcarl79** [indrimuska/angular-moment-picker#145]
Hi,

See the example below, I can't seem to get the format date to work in this scenario, is there something wrong in the plnkr example below?

[https://embed.plnkr.co/0ZHLp3MuzFDhgOLjnayM/](https://embed.plnkr.co/0ZHLp3MuzFDhgOLjnayM/)

Thanks in advance, definitely the best looking angular date/time picker out there so would love to get it working in my app :)

**Comment by mouss-delta** [comment]
Hi,

The problem may come from the fact that you are using 2 different variables : momentDate and formattedDate. 

The input is binded to the variable momentDate, and in the controller you set this variable like this `$scope.momentDate = moment();` so it is normal that the date is not formatted inside the input, if you want it to be formatted, you need to initialise this variable like this : `$scope.momentDate = moment().format('YYYY-MM-DD');`, I have tried an it works.

However I think that you are missing a point, because the variables momentDate and formattedDate are not synchronised so whatever you chose in the picker will not appear inside the input. To make this work see this plunker : https://plnkr.co/edit/0ZHLp3MuzFDhgOLjnayM?p=preview

**Comment by indrimuska** [comment]
Thanks @mouss-delta to have fully explained the problem and have shown the solution.

**Comment by mouss-delta** [comment]
@indrimuska : you are very welcome :)
