### ISSUE TITLE
Clearing model and setting form pristine

### ISSUE THREAD

**Issue by easyest** [indrimuska/angular-moment-picker#149]
My goal - clear input and make form pristine again. To clear the picker I set model to undefined or null. After that I try to set the form pristine, but it does not happen.

Please see the plunk: https://plnkr.co/edit/NZUNOe6jZYcITgprwk18
Expected - form is pristine (button is grey) after button click.
Result - form is pristine only after second click on the button. In other words - moment-picker model change somehow prevents the form from becoming pristine.

**Comment by indrimuska** [comment]
Hi @easyest, I deeply analyzed your example and I found the problem why your form needs a double click that Clear button.

After debugging a little, I notice that $pristine flag on the input is set when $commitViewValue is called on the entire form. This is done by Angular when you submit the form. The reason why you are submitting the form is that your button does not have a `type` property set, so by default it will have a `type="submit"` value.

The callback on your button is fired AFTER form submission, so there's a tiny piece of time when your input is properly set to a `$pristine` state. But after that, submission is fired and Angular commits its value setting all this fields to a `$dirty` state. I think that the second time you hit the "clear" button the value of your field does not change, so Angular does not need to call the `$commitViewValue` method.

Anyway, solution is easier than debugging. You can just set `type="button"` on your button or call your callback after submission (attaching it to the `ng-submit` directive on the form).

Hope this helps, I'll close this issue since it's not due to Angular Moment Picker.
Feel free to comment for any trouble. :)

**Comment by easyest** [comment]
Button type works in initial plunk. Could You please look at the updated plunk at https://plnkr.co/edit/NZUNOe6jZYcITgprwk18
