### ISSUE TITLE
Changing locale dynamically

### ISSUE THREAD

**Issue by GeorgeKnap** [indrimuska/angular-moment-picker#37]
I would like to request putting the **locale** property under watch to allow changing the language dynamically.

Currently I set the local property to my controller's view model's property like this:
`data-locale="{{ctrl.data.momentPickerLanguage}}"`

When I change my app language I set the new value to this view model's property e.g. 'en' but the input field text does not refresh the language.

Thank you.
George

**Comment by indrimuska** [comment]
Hi @GeorgeKnap, listening to the dynamic change of the locale is not so easy as you can see from the online builder. That's because any `min` (or `max`) value set for the picker is a string and it must be converted from the previous locale to the new one.

Anyway it can be an interesting feature so let's go for it.

**Comment by GeorgeKnap** [comment]
Hi @indrimuska 
Many thanks! I'm sure it will be a valuable feature to your component.

George

**Comment by indrimuska** [comment]
@GeorgeKnap v0.5.4 has this new feature, enjoy! :)
