### ISSUE TITLE
Having another format for database

### ISSUE THREAD

**Issue by dreammeup** [indrimuska/angular-moment-picker#50]
Hello,

You have done a really good work on that AngularJS picker.

I think there is something missing, and that could be very usefull. Or maybe I just didn't find it.

The format of the date you are displaying for the user is generally not the same as the format you want to save in your database.

So I think it will be interesting to define another format for the saving, and a ng-model to populate with that value, for example to fill an input hidden.

So the input text will contain for example "July 15, 2016 10:35:14 AM"
And the input hidden (for the database) : "2016-07-15 10:35:14".

Do you think it's a feature you could add ?

Best Regards,

**Comment by indrimuska** [comment]
Hi @dreammeup, thank you for the nice words!
I think this should be a part of the users app, but not integrated in the directive itself. That's because the format of the database depends of which one you use (e.g MySQL uses the format `YYYY-DD-MM HH:ii`, but MongoDB makes use of integer timestamps).

Anyway, that's absolutely not hard to implement, you just need a $watcher to make it real, like this:

```javascript
```

**Comment by dreammeup** [comment]
Hello,

Thanks for the solution.

I didn't knew how to convert easily the date.

Bye.
