### ISSUE TITLE
Selected Date data type is coming with String format

### ISSUE THREAD

**Issue by vishnureddy** [indrimuska/angular-moment-picker#81]
Hi,
I am using moment date-picker. Its working nice. But after selecting the date,  data type of selected date is coming with string for some reason. But if it comes with Date data type it will be amazing for me.

Thanks.

**Comment by indrimuska** [comment]
Hi @vishnureddy, unfortunately that's not possible at the moment, and I don't think it will never be. However, in the next big release I am planning to return entire Moment.js object so that you can handle date object in a more efficient way.

If you want to have a look and leave a feedback you should check at https://github.com/indrimuska/angular-moment-picker/issues/60#issuecomment-254596657.
Thanks :)
