### ISSUE TITLE
Allow to accept the options as an element attribute

### ISSUE THREAD

**Issue by dhiman252** [indrimuska/angular-moment-picker#88]
Like there is moment-picker="myDate" can there be the moment-picker-options="{ locale:         'en',
				format:         'L LTS',
				minView:        'decade',
				maxView:        'minute',
				startView:      'year',
				autoclose:      true,}"

**Comment by indrimuska** [comment]
Hi @dhiman252, this could be an interesting feature, but I think that should be more powerful for each user to create its own angular Component, in order to configure several set of datepickers as they want.

You can take inspiration on [this comment](https://github.com/indrimuska/angular-moment-picker/issues/63#issuecomment-249671990) or just use Moment Picker Provider if you have just configuration for all your pickers.

Thanks :)
