### ISSUE TITLE
Allow to set first year in decade view

### ISSUE THREAD

**Issue by mathieu-morchipont** [indrimuska/angular-moment-picker#89]
Can i set first year in decade view when it's was in first ? Sorry for my english ;)

**Comment by indrimuska** [comment]
Hi @mathieu-morchipont, do you want to choose which year is the first in decade view?

**Comment by mathieu-morchipont** [comment]
Yes , if startYear is to set 1989, the decade view is 1989 -1999

**Comment by indrimuska** [comment]
Oh ok, I think you want to choose the first decade to be shown every time the picker will be opened.
Sorry, but actually there's no way to that. You can just set you picker to the a valid year in that period, but it's quite different, since a date has been set and you will lost that decade to be shown when the picker opens after each model reset (blank or null).

For your use case, I suggest a new property called `startDate` as String or Moment Object.
This is just a proposal, because I don't have too much spare time to code it by myself, but if you want to propose a PR I'll be happy to review it! :)

**Comment by mathieu-morchipont** [comment]
Can you review https://github.com/indrimuska/angular-moment-picker/pull/97

**Comment by indrimuska** [comment]
@mathieu-morchipont I haven't forgot your PR, I'm going to review it as soon as I can. :) thanks

**Comment by indrimuska** [comment]
`startDate` is now available starting from [v0.8.3](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.8.3).
