### ISSUE TITLE
Month View for February/March not displayed properly

### ISSUE THREAD

**Issue by sashawilcox** [indrimuska/angular-moment-picker#9]
When displaying February 2016 month view, the dates are not displayed properly.

Similar issue occurs with subsequent February/March months. May be due to February having  a different number of days each year..?

![angular_moment_picker_1](https://cloud.githubusercontent.com/assets/12714285/12679847/c8410f3a-c67c-11e5-9989-6095d069f026.png)
![angular_moment_picker_2](https://cloud.githubusercontent.com/assets/12714285/12679848/c84599f6-c67c-11e5-9672-4a536153cad2.png)
![angular_moment_picker_3](https://cloud.githubusercontent.com/assets/12714285/12679849/c8490672-c67c-11e5-80b6-bc6414bd91b5.png)

**Comment by indrimuska** [comment]
Hi @sashawilcox, thank you for reporting this.
Unfortunately I am unable to see this issue, as you can see in the [demo page](http://indrimuska.github.io/angular-moment-picker/) February looks correct.
So, could you share your full configuration or provide a working example? Thanks

**Comment by sroutledge** [comment]
Hi @indrimuska, I'm a dev on the same project. We're using version 0.1.3 of angular-moment-picker, and version 0.2.2 of angular-momentjs. I'm able to reproduce this with the default configuration and as basic a template as:

<input moment-picker="ctrl.date"/>

(ctrl.date starts null)

**Comment by indrimuska** [comment]
Thank you @sroutledge for confirming this bug, but I really can't reproduce that behavior.
This is the [plunker](http://plnkr.co/edit/pl29UIeSdLTqWFmOWLb8?p=preview) I tested, but I can't see anything strange or incorrect in it.
Could you please help me to understand where the problem is, just updating that plunker?
Thanks

**Comment by sroutledge** [comment]
@indrimuska 

I was able to narrow it down to the version of angular we're using:

http://plnkr.co/edit/TwpUvqD1dQOfU3wIopQ2

Seems that it happens with angular versions 1.3.x (1.3.20 in our case)

Angular version 1.4.0 works as expected. We will look at upgrading our version of angular. 

Thank you for your time!!

**Comment by sroutledge** [comment]
Adding: since the 1.4.0 update introduced some breaking changes for Angular, we may not be able to upgrade right away. If you can implement a fix for 1.3.x versions of Angular, that would be awesome, too!

**Comment by indrimuska** [comment]
Good to know @sroutledge, give me some days to see the difference between these two versions.

@sashawilcox can you confirm that your issue is caused by the version of Angular?

**Comment by indrimuska** [comment]
Ok, I think the problem is this ([doc](https://code.angularjs.org/1.3.19/docs/api/ng/directive/ngRepeat#iterating-over-object-properties)):
> Angular versions up to and including 1.3 sort the keys alphabetically.

Since Angular Moment picker uses an object of weeks where the keys is the number of the week in the year, and since weeks of February 2016 start from 6th to 11th, I think that Angular sorts the object using this order: 10, 11, 6, 7, 8, 9. That is because it uses an alphabetical sort, not a natural or a similar sort.

Maybe I could release a unique version available even for this version of Angular. :)

**Comment by sashawilcox** [comment]
Thanks @indrimuska! I can confirm that's it's caused by the Angular version :smile:

**Comment by indrimuska** [comment]
FYI this is now available in [0.2.1](https://github.com/indrimuska/angular-moment-picker/releases/tag/0.2.1).
Thank you all for reporting this! :)
