### ISSUE TITLE
dateformat issue

### ISSUE THREAD

**Issue by sadashivm** [indrimuska/angular-moment-picker#92]
Hi im using latest version (v.0.8). im facing some problem like,

```
<input type="text" moment-picker="dt.deliveryDueDate"  ng-model="dt.deliveryDueDate"
     format="DD MMM YYYY" start-view="month" ng-model-options="{ updateOn: 'blur' }"  />
<input type="button" ng-click="getdt()" />
```

in controller i have written 
```
$scope.getdt = function() {
var x = $scope.dt.deliveryDueDate;
alert(x);
}
```

![error1](https://cloud.githubusercontent.com/assets/10355473/20711408/8fb028ca-b665-11e6-8044-82603f8f746a.png)

i have already written date format attribute in element then why it is not coming only like "Nov 16 2016"

and one more 

```
$scope.getdt = function() {
var x = $scope.dt.deliveryDueDate;
console.log(x);
}
```
if console x then im getting value like 

![error2](https://cloud.githubusercontent.com/assets/10355473/20711640/bd7b5968-b666-11e6-8087-ce479eb704d6.png)
![error3](https://cloud.githubusercontent.com/assets/10355473/20711641/bd7d1712-b666-11e6-9335-0d6455fec72f.png)

can you tell me why it is coming like this.
in previous version(v.0.6) it is coming properly in new version it is not coming

i  want output only "Nov 16 2016".

pls reply me as early as possible

**Comment by indrimuska** [comment]
Hi @sadashivm,  you're facing an issue due to how the picker works in the latest release when using ng-model.

In this revision I've introduced a new way to handle full date objects (not available until v0.7) and formatted date strings: `ngModel` property is now used to get the full Moment.js object of the selected date, instead `momentPicker` has the formatted string date using the appropriate `format`. This way, you can achieve the formatted string in 2 ways:

1. **Using formatted string date coming from `moment-picker` attribute**
   ```html
   <input moment-picker="ctrl.formattedDate"
          ng-model="ctrl.momentDate"
          ng-model-options="{ updateOn: 'blur' }"
          format="DD MMM YYYY"
          start-view="month">
   
   <!-- Use `ctrl.formattedDate` anywhere -->
   Formatted date: {{ ctrl.formattedDate }}
   ```
2. **Retrieving the formatted date using the Moment.js object**
   ```html
   <input moment-picker
          ng-model="ctrl.momentDate"
          ng-model-options="{ updateOn: 'blur' }"
          format="DD MMM YYYY"
          start-view="month"
          change="ctrl.setFormattedDate(newValue)">
   
   <!-- Use `ctrl.formattedDate` anywhere -->
   Formatted date: {{ ctrl.formattedDate }}
   ```
   ```javascript
   ctrl.setFormattedDate = function (momentDate) {
      // do you stuff.. and
      ctrl.formattedDate = momentDate.format('DD MMM YYYY');
   };
   ```

---
**Notes:**
 - If you choose option 1, keep in mind to use two different model for `moment-picker` and for `ng-model` properties (even if you don't use them).
 - The model for `moment-picker` property is not required, rather than the mandatory `ng-model` when using an `<input>` field.
 - Using the **same the same model** for those properties (as you're doing) will cause the overriding of the formatted date in favor of Moment object.

**Comment by sadashivm** [comment]
thank for updating dear, its working fine

**Comment by indrimuska** [comment]
Glad this helped you! :)

**Comment by wannado** [comment]
[cant get this working](https://plnkr.co/edit/nfl49pOnI7sSrovmNTKP?p=preview)

I have initial value coming in as '2017-02-07T19:00:00.000Z'  and need to display as DD-MMM-YYYY HH:[00] A but beed to submit back as  string  format '2017-02-07T19:00:00.000Z'

**Comment by josephpedro** [comment]
Hi,

First off all good job with this library, I've been struggling with the javascript date object mostly when using different timezones.
I'm receiving a date from a server in two formats, a javascript date ( which gives me problems regarding timezones) and in a string format (ISO 8601. I'm trying to show the date in the datepicker in the format "dd/mm/yyyy" using the attribute format but the dates is displayed like this "Fri Jun 24 2016 00:00:00 GMT+0000". 

Here is my config:

omentPickerProvider.options({
        /* Picker properties */
        format: 'DD/MM/YYYY',
        minView: 'year',
        maxView: 'day',
        startView: 'year',
        autoclose: true,
        today: false,
        keyboard: false,

        /* Extra: Views properties */
        leftArrow: '&larr;',
        rightArrow: '&rarr;',
        yearsFormat: 'YYYY',
        monthsFormat: 'MMM',
        daysFormat: 'D',
        hoursFormat: 'HH:[00]',
        minutesFormat: moment.localeData().longDateFormat('LT').replace(/[aA]/, ''),
        secondsFormat: 'ss',
        minutesStep: 5,
        secondsStep: 1
    });

<div class="input-group"
   moment-picker="item.EndDateString">
 <span class="input-group-addon">
     <i class="glyphicon glyphicon-calendar"></i>
  </span>
   <input class="form-control" placeholder="Select a date"
            ng-model="EndDateMoment" ng-model-options="{ updateOn: 'blur' }">
</div>

**Comment by indrimuska** [comment]
Hi @josephpedro, thanks for the kind words.

Be careful when using momentPicker directive with ngModel in two different DOM elements.
In your case `EndDateMoment` is not related to moment-picker, it is just a two-way bindable property that does not make use of the picker. If you want to use momentPicker with both formatted string and moment.js object you have to add the directive in the same place (same DOM element). The point where you place the moment-picker directive is used as anchor point for the picker itself, so that you can put whatever you want on the inside.

```html
<div class="input-group"
     moment-picker="item.EndDateString"
     ng-model="item.EndDateMoment">
   <span class="input-group-addon">
      <i class="glyphicon glyphicon-calendar"></i>
   </span>
   <input class="form-control"
          placeholder="Select a date"
          ng-model="item.EndDateMoment"
          ng-model-options="{ updateOn: 'blur' }">
</div>

<!-- You can use picker properties wherever you want! -->
<p>Formatted string: {{ item.EndDateString }}</p>
<p>Duplicate input: <input ng-model="item.EndDateMoment"></p>
```

Hope this helps!

**Comment by indrimuska** [comment]
Hi @wannado,
In your plunker you are using different formats for the picker, in particular you've initialized `datepicker` to `"2017-02-07T19:00:00.000Z"` and you want to use that string in the format `DD/MM/YYYY HH:[00] A`.

In your use case you just need to set `datepicker` to `"07/02/2017 20:00 PM"`.

**Comment by ConstantineStehoff** [comment]
I am getting the formatted date in input ng-model but when I try to edit it (in the input field) or type a new one I get some weird behavior... 
Here is what I am doing now:

```
<input type="text" ng-model="formattedFromDate">
<span moment-picker="formattedFromDate" ng-model-options="{ updateOn: 'blur' }" ng-model="fromDate" position="bottom right" format="MM/DD/YYYY" start-view="month" today="true" keyboard="true" min-view="month" max-view="month">......</span>
```

Basically I want to edit ng-model (that is connected to the datepicker) in the input field. Can I do that?

**Comment by indrimuska** [comment]
Sure @sadashivm, what do you mean with _weird behavior_? Can you please provide a sample to show that?
